server.port: 8080
spring:
  profiles.active: local

  datasource:
    url: jdbc:mysql://${db.host}/${db.schema}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
#        org.hibernate.dialect.MySQL5Dialect
  output.ansi.enable: always

  flyway:
     url: jdbc:mysql://${db.host}:${db.port}/${db.schema}
     user: ${db.username}
     password: ${db.password}
  #   baseline-on-migration: true
     baselineOnMigrate: true
     locations: classpath:db/migration
     enabled: true
